### PR TITLE
adds more registry contract tests

### PR DESCRIPTION
**Pull request by BlazeWasHere**
* test: add registry as tuple and array

View https://github.com/alisinabh/elixir_ethers/pull/46#pullrequestreview-1691608400

### CODE REVIEW

**Comment by BlazeWasHere** [comment]
This PR requires #46 to be merged first, or should I change the target branch?

**Comment by alisinabh** [comment]
> This PR requires #46 to be merged first, or should I change the target branch?

Good point. I thibk we should make the checks pass here and merge first then focus on the change in your other PR.

Thank you.

**Comment by BlazeWasHere** [comment]
> > This PR requires #46 to be merged first, or should I change the target branch?
> 
> Good point. I thibk we should make the checks pass here and merge first then focus on the change in your other PR.
> 
> Thank you.

I think it would be best to merge the other PR first (which should be conflict free to this PR), rather than add to this PR -> merge the other PR -> fix tests (which would now be broken, because of prior PR).

**Comment by alisinabh** [comment]
❤️ 💚 ❤️ 💚

**Pull request merged**
